name: CI Test Global Env
on:
  workflow_dispatch:

jobs:
  setenv:
    name: Set Env Variable Globaly
    runs-on: ubuntu-latest
    outputs:
      should-work: ${{ steps.setter.outputs.should-work }}
      my-secret-output: ${{ steps.setter.outputs.my-secret-output }}
      my-encoded-output: ${{ steps.setter.outputs.my-encoded-output }}

    steps:
      - uses: actions/checkout@v3
      - name: Setter
        id: setter
        run: |
          echo "${{ secrets.NO_SECRET }} >> $GITHUB_ENV"
          echo "SIMPLE_VAR=${{ env.SIMPLE_VAR }}"
          echo "should-work=v4.2" >> $GITHUB_OUTPUT
          echo "my-secret-output=${{ env.SIMPLE_VAR }}" >> $GITHUB_OUTPUT
          echo "my-encoded-output=$(echo "v4.${{ secrets.TOO_SIMPLE_SECRET }}" | base64)" >> $GITHUB_OUTPUT
      - name: Getter in same job
        run: |
          echo "still ok ? env.SIMPLE_VAR=${{ env.SIMPLE_VAR }}"
  
  getenv:
    needs: setenv
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Getter in other job
        run: |
          echo "env.SIMPLE_VAR=${{ env.SIMPLE_VAR }}"
          echo "needs.setenv.outputs.should-work=${{ needs.setenv.outputs.should-work }}"
          echo "needs.setenv.outputs.my-secret-output=${{ needs.setenv.outputs.my-secret-output }}"
          echo "needs.setenv.outputs.my-encoded-output=${{ needs.setenv.outputs.my-encoded-output }}"
          echo "DECODED needs.setenv.outputs.my-encoded-output=$(echo "${{ needs.setenv.outputs.my-encoded-output }}" | base64 -d)"
